from .prompts import (
    MARKET_ANALYST, FUNDAMENTALS_ANALYST, NEWS_ANALYST, SOCIAL_ANALYST,
    BULL_RESEARCHER, BEAR_RESEARCHER, RESEARCH_MANAGER,
    BATTLE_CRITIC, BATTLE_SYNTHESIZER,
    TRADER, AGGRESSIVE_ANALYST, CONSERVATIVE_ANALYST, NEUTRAL_ANALYST,
    PORTFOLIO_MANAGER,
)

__all__ = [name for name in dir() if name.isupper()]
